export const IS_LOGIN = "IS_LOGIN"
export const TOKEN = "TOKEN"
export const ORDER = "order"
export const INFORMATION = "information"
const ORDERS = "orders"
export const PRODUCT_GET_PRODUCT = "PRODUCT_GET_PRODUCT" ;
export const PRODUCT_GET_SINGLE_PRODUCT = "PRODUCT_GET_SINGLE_PRODUCT" ;
export const PRODUCT_GET_SINGLE_CATEGORY = "PRODUCT_GET_SINGLE_CATEGORY" ;
export const CART_CHANGE_STATE = "CART_CHANGE_STATE" ;
export const CATEGORY_GET_CATEGORY = "CATEGORY_GET_CATEGORY" ;
export const ORDERS_GET_ORDERS = "ORDERS_GET_ORDERS"
export const REACT_APP_BASE_URL = "http://localhost:3002" ;